sudo: required
language: python
python:
    - "3.8"

install:
    - pip install -r requirements.txt 

script:
    - pwd
    - python3 -m test_discovery_helper_util
    - pytest --cov
after_success: "coveralls"

